### ISSUE TITLE
README not up to date

### ISSUE THREAD

**Issue by Thomas-Ulrich** [jsh9/fast-konno-ohmachi#1]
Hi,

Thank you for this script.
I noted that the README in not up to date with the interface of the function (e.g. there is no verbose option).
```
import konno_ohmachi as ko
smoothed = ko.fast_konno_ohmachi(spectrum, freq, smooth_coeff=40, verbose=True)
```
Also, you could consider making a pip module (see e.g. https://dzone.com/articles/executable-package-pip-install), so that user could install your module with:
`pip install fast-konno-ohmachi`

Thomas.

**Comment by jsh9** [comment]
Hi @Thomas-Ulrich , thanks for your interest.  I'm pleasantly surprised to find that people are interested in my old code (from almost 10 years ago).

I made some changes (https://github.com/jsh9/fast-konno-ohmachi/pull/2) to turn this into an installable Python library.  You can now install it via pip install: https://pypi.org/project/fast-konno-ohmachi/
