### ISSUE TITLE
Error with few number of sample

### ISSUE THREAD

**Issue by korroziveLab** [jsh9/fast-konno-ohmachi#1]
Hi i'm testing your code because i'm looking for a fast konno ohmachi solution, but comparing it with obspy's implementation and one of my own, your code can't smooth properly in lower frequencies a spectra with few number of samples. 
 I'm posting an example of my benchmarking
![fas_ko](https://user-images.githubusercontent.com/26774206/32736085-98273de2-c864-11e7-8598-de76ecc7b682.png)

Also, results from Slow and Fast implementation are very different 
![fas_ko2](https://user-images.githubusercontent.com/26774206/32736290-0ef15066-c865-11e7-9cd2-72ac6aa5c41b.png)

Please check it

Thanks in advance

**Comment by jsh9** [comment]
Hey, somehow I didn't receive any notifications when people post issues... Sorry about that!

I will check asap.

**Comment by jsh9** [comment]
I adjusted slow_konno_ohmachi slightly, so that it is consistent with fast_konno_ohmachi.

But I do not quite know why my codes generate slightly different results in low-frequency than yours and geopsy.  Maybe you can compare your code with slow_konno_ohmachi and find out the reason?
